# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-07 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(choices=[(3, 'Captain'), (2, 'Field player'), (0, 'Inactive'), (-1, 'Invited'), (-2, 'Asked to join'), (1, 'Substitute')], default=-1)),
            ],
            options={
                'ordering': ['-role'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('slots_female', models.IntegerField(default=0, null=True)),
                ('slots_male', models.IntegerField(default=0, null=True)),
                ('type', models.IntegerField(choices=[(0, 'Coed'), (1, 'Female'), (2, 'Male')], default=0)),
            ],
        ),
    ]
