# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-27 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='slots_female',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='slots_male',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='type',
            field=models.IntegerField(choices=[(0, 'Coed'), (1, 'Female'), (2, 'Male')], default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
