# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-25 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20161207_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='info',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
