# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-13 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20161209_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
