# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-30 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20170819_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
    ]
