---
language: python
python: '3.6'

notifications:
  slack: gffc:oVo9Dqq6azm2JGu6Wa052sQC

services:
  - postgresql

addons:
  ssh_known_hosts:
    - goodfoot.club
    - dev.goodfoot.club

env:
  global:
    - ANSIBLE_PRIVATE_KEY_FILE=$TRAVIS_BUILD_DIR/config/ssh_key
    - ANSIBLE_SSH_PIPELINING=True

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-apt python-pycurl
  - export DJANGO_SETTINGS_MODULE=gfc.settings.travis

install:
  - psql -U postgres -c "create extension postgis"
  - pip install -r requirements.txt

script:
  - py.test


before_deploy:
  - deactivate
  - source ~/virtualenv/python2.7/bin/activate
  - pip install ansible==2.1.2
  - >-
    openssl aes-256-cbc -K $encrypted_b483be284343_key -iv
    $encrypted_b483be284343_iv -in config/ssh_key.enc -out config/ssh_key -d
  - chmod 600 config/ssh_key
  - echo dev.goodfoot.club > inventory_dev
  - echo goodfoot.club > inventory_prod

deploy:
  - provider: script
    skip_cleanup: true
    script: ansible-playbook -i inventory_dev config/deploy.yml -e "env=dev"
    on:
      branch: develop

  - provider: script
    skip_cleanup: true
    script: ansible-playbook -i inventory_prod config/deploy.yml -e "env=prod"
    on:
      branch: master
