# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-12 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20161107_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsvpstatus',
            name='status',
            field=models.CharField(choices=[('G', 'G'), ('N', 'N'), ('U', 'U')], default='U', max_length=1),
        ),
    ]
