# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-12 11:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20161112_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamrole',
            name='player',
        ),
        migrations.RemoveField(
            model_name='teamrole',
            name='team',
        ),
        migrations.AlterField(
            model_name='team',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_managed_teams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='players',
            field=models.ManyToManyField(related_name='old_teams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='TeamRole',
        ),
    ]
