# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-13 18:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20161112_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_games', to='main.Location'),
        ),
        migrations.AlterField(
            model_name='game',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_games_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='game',
            name='teams',
            field=models.ManyToManyField(related_name='old_games', to='main.Team'),
        ),
        migrations.AlterField(
            model_name='rsvpstatus',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_rsvps', to='main.Game'),
        ),
        migrations.AlterField(
            model_name='rsvpstatus',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_rsvps', to=settings.AUTH_USER_MODEL),
        ),
    ]
