---

- name: Deploy the project on a remote server
  hosts: all
  become: yes
  become_user: root
  remote_user: ubuntu

  vars:
    deploy: true
    repo: https://github.com/goodfootclub/api.git

  tasks:
  - name: Run apt-get update
    apt: update_cache=yes

  - name: Ensure that git is installed
    apt: name=git state=present

  - name: Ensure that project files are updated
    git: repo={{ repo }} dest=/home/ubuntu/api


- include: site.yml home=/home/ubuntu
