---

- name: Deploy the project on a remote server
  hosts: all
  become: yes
  become_user: root
  remote_user: ubuntu

  vars:
    deploy: true
    repo: https://github.com/goodfootclub/api.git

  tasks:
  - name: Run apt-get update
    apt: update_cache=yes

  - name: Ensure that git is installed
    apt: name=git state=present

  - name: Ensure that project files are updated
    # TODO: replace with syncronize, makes more sense
    # http://docs.ansible.com/ansible/synchronize_module.html
    git: repo={{ repo }} dest=/home/ubuntu/api force=yes

- include: site.yml srv=/home/ubuntu remote_user=ubuntu use_ssl=true
