# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-07 14:13
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('duration', models.IntegerField(null=True)),
            ],
            options={
                'ordering': ['datetime'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('gis', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RsvpStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(2, 'Going'), (-1, 'Invited'), (0, 'Not going'), (-2, 'Asked to join'), (1, 'Not sure')], default=-1)),
                ('team', models.IntegerField(default=2)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to='games.Game')),
            ],
            options={
                'ordering': ['-status'],
                'verbose_name_plural': 'RSVP statuses',
                'verbose_name': 'RSVP status',
            },
        ),
    ]
