# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-13 19:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rsvpstatus',
            options={'ordering': ['-status'], 'verbose_name': 'RSVP status', 'verbose_name_plural': 'RSVP statuses'},
        ),
        migrations.AddField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(related_name='games', through='games.RsvpStatus', to=settings.AUTH_USER_MODEL),
        ),
    ]
