# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-13 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20161113_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsvpstatus',
            name='status',
            field=models.IntegerField(choices=[(2, 'Going'), (-1, 'Invited'), (0, 'Not going'), (-2, 'Asked to join'), (1, 'Not sure')], default=-1),
        ),
    ]
