# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-29 17:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_auto_20170122_1824'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='location',
            unique_together=set([('address', 'name')]),
        ),
    ]
