# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-29 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_auto_20170129_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
