# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-23 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_auto_20170419_1657'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rsvpstatus',
            options={'ordering': ['game__datetime', '-status'], 'verbose_name': 'RSVP status', 'verbose_name_plural': 'RSVP statuses'},
        ),
        migrations.AddField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
